# FRC Match Team Metrics
Displays the historical metrics of teams at an event.

## Setup
In your virtual environment, install pandas and matplotlib: 
  `pip install pandas matplotlib`
* If you are using VS Code, it should ask you to install the IPython extensions.
* If this next cell runs with no errors, you are all set.

In [1]:
import util
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

## Functions to get Team and Event names
Some parts of this notebook depend on a team you are interested in.  Other parts of this notebook need to look up the team name.  This section defines a function to look up the team name.  Same things for event name.

In [2]:
def get_team_name(team_id):
    url = f'https://www.thebluealliance.com/api/v3/team/{team_id}'
    return util.call_tba_api(url).json()['nickname']

def get_event_name(event_id):
    url = f'https://www.thebluealliance.com/api/v3/event/{EVENT_KEY}/simple'
    resp = util.call_tba_api(url).json()
    return str(resp['year']) + ' ' + resp['name']

## Default Team and Event

In [3]:
YEAR = '2025'
TEAM = 'frc6223'
EVENT_KEY = '2025wimu'
# EVENT_KEY = '2025wimi'

TEAM_NAME = get_team_name(TEAM)
EVENT_NAME = get_event_name(EVENT_KEY)

print(TEAM_NAME, 'at', EVENT_NAME)

Arsenal of Engineering at 2025 Phantom Lakes Regional

## Teams at the Event

In [4]:
url = f'https://www.thebluealliance.com/api/v3/event/{EVENT_KEY}/teams/simple'
resp = util.call_tba_api(url).json()
df = pd.DataFrame.from_dict(resp, orient='columns')
print('Team count: ', str(len(df)))
del url, resp
df.drop(columns=['country', 'name', 'team_number'], inplace=True)
df

Team count:  41

,city,key,nickname,state_prov
0,Menomonie,frc10264,STORM,Wisconsin
1,Oregon,frc10553,Orange Overdrive,Wisconsin
2,Hartford,frc1091,Oriole Assault,Wisconsin
3,Milwaukee,frc1220,Rockhoppers - Hilltopper Robotics,Wisconsin
4,Middleton,frc1306,BadgerBOTS,Wisconsin
5,Milwaukee,frc1714,MORE Robotics,Wisconsin
6,Milwaukee,frc1732,Hilltopper Robotics,Wisconsin
7,Oak Creek,frc1792,Round Table Robotics,Wisconsin
8,Waukesha,frc2062,CORE 2062,Wisconsin
9,Wales,frc2077,Laser Robotics,Wisconsin
10,Brookfield,frc2202,BEAST Robotics,Wisconsin
11,Rockford,frc2290,FLYT,Illinois
12,Rochester,frc2530,Inconceivable,Minnesota
13,Burnsville,frc3184,Blaze Robotics,Minnesota
14,Queretaro,frc3354,PrepaTec - TecDroid,Querétaro
15,Janesville,frc3692,Rock N' Robotics,Wisconsin
16,Becker,frc4607,C.I.S.,Minnesota
17,Monterrey,frc4635,PrepaTec - Botbusters,Nuevo León
18,Rockford,frc4693,Talk Nerdy to Me,Minnesota
19,Milwaukee,frc4786,Nicolet FEAR,Wisconsin
20,New Berlin,frc5148,New Berlin Blitz,Wisconsin
21,DeKalb,frc5934,Crowbotics,Illinois
22,Cuernavaca,frc5948,PrepaTec - Lebotics,Morelos
23,Bakirköy,frc5993,Istech Robotics Society,Istanbul
24,Mumbai,frc6024,R Factor,Maharashtra
25,Holmen,frc6166,Thorobotics,Wisconsin
26,Menomonee Falls,frc6223,Arsenal of Engineering,Wisconsin
27,Davenport,frc6317,Disruptive Innovation,Iowa
28,Freedom,frc6318,FE Freedom Engineers,Wisconsin
29,Sheboygan,frc6381,Red Raider Robotics,Wisconsin
30,Muskego,frc6421,WarriorBots,Wisconsin
31,Whitewater,frc6574,Ferradermis,Wisconsin
32,Racine,frc6643,Walnuts and Bolts,Wisconsin
33,Taipei,frc6947,Savage Tumaz,Taipei Special Municipality
34,Williamsfield,frc7417,Bionic Bombers,Illinois
35,Racine,frc7900,Trial N' Terror,Wisconsin
36,Waupaca,frc8700,W.I.R.E.D,Wisconsin
37,Greendale,frc8701,GRAFFITI,Wisconsin
38,Marinette,frc8803,MechaMarines,Wisconsin
39,Mukwonago,frc930,Mukwonago BEARs,Wisconsin
40,Troy,frc9401,Midas' Mayhem,Missouri

## Loop through teams to get metrics

In [5]:
df2 = pd.DataFrame(columns=['key', 'events', 'qual_wins', 'qual_loss', 'qual_ties', 'poff_wins', 'poff_loss', 'poff_ties', 'ranking'])
print('Researching:', end="")
for team in df['key']:
    print('.', end="")
    
    matches = 0
    qual_wins = 0
    qual_loss = 0
    qual_ties = 0
    poff_wins = 0
    poff_loss = 0
    poff_ties = 0
    ranking = []
    
    
    url = f'https://www.thebluealliance.com/api/v3/team/{team}/events/{YEAR}/statuses'
    resp = util.call_tba_api(url).json()
    
    for match in resp:
        details = resp[match]
        
        if details != None and details['qual'] != None:
            matches += 1
            qual_wins += details['qual']['ranking']['record']['wins']
            qual_loss += details['qual']['ranking']['record']['losses']
            qual_ties += details['qual']['ranking']['record']['ties']
            if details['playoff'] != None:
                poff_wins += details['playoff']['record']['wins'] 
                poff_loss += details['playoff']['record']['losses'] 
                poff_ties += details['playoff']['record']['ties'] 
            ranking.append(details['qual']['ranking']['rank'])

    df2.loc[len(df2)] = [team, matches, qual_wins, qual_loss, qual_ties, poff_wins, poff_loss, poff_ties, 0 if ranking is None or len(ranking) == 0 else sum(num for num in ranking if num is not None) / len(ranking)]
    # print('  ', matches, qual_wins, qual_loss, qual_ties, poff_wins, poff_loss, poff_ties, ranking)
    
df = df.join(df2.set_index('key'), on='key')
del df2

Researching:.........................................

In [6]:
# Set all ranking = 0 to 100
df['ranking'] = df['ranking'].replace(0, 100)

# Calculate win rates
df['win_qual'] = df['qual_wins'] / (df['qual_wins'] + df['qual_loss'] + df['qual_ties'])
df['win_poff'] = df['poff_wins'] / (df['poff_wins'] + df['poff_loss'] + df['poff_ties'])

# Convert the decimal column to percentages
df['win_qual'] = df['win_qual'].apply(lambda x: f"{x * 100:.0f}%")
df['win_poff'] = df['win_poff'].apply(lambda x: f"{x * 100:.0f}%")

In [7]:
#df.sort_values(by=['ranking', 'win_qual'], ascending=[True,False], inplace=True, ignore_index=True)
df.sort_values(by=['win_qual'], ascending=[False], inplace=True, ignore_index=True)
df

,city,key,nickname,state_prov,events,qual_wins,qual_loss,qual_ties,poff_wins,poff_loss,poff_ties,ranking,win_qual,win_poff
0,Menomonie,frc10264,STORM,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
1,Mukwonago,frc930,Mukwonago BEARs,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
2,Milwaukee,frc1220,Rockhoppers - Hilltopper Robotics,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
3,Marinette,frc8803,MechaMarines,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
4,Racine,frc7900,Trial N' Terror,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
5,Oak Creek,frc1792,Round Table Robotics,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
6,Racine,frc6643,Walnuts and Bolts,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
7,Wales,frc2077,Laser Robotics,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
8,Brookfield,frc2202,BEAST Robotics,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
9,Menomonee Falls,frc6223,Arsenal of Engineering,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
10,Rochester,frc2530,Inconceivable,Minnesota,0,0,0,0,0,0,0,100.0,nan%,nan%
11,Bakirköy,frc5993,Istech Robotics Society,Istanbul,0,0,0,0,0,0,0,100.0,nan%,nan%
12,Oregon,frc10553,Orange Overdrive,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
13,Milwaukee,frc4786,Nicolet FEAR,Wisconsin,0,0,0,0,0,0,0,100.0,nan%,nan%
14,Milwaukee,frc1732,Hilltopper Robotics,Wisconsin,1,8,1,0,3,2,0,3.0,89%,60%
15,Monterrey,frc4635,PrepaTec - Botbusters,Nuevo León,2,19,3,0,7,2,0,1.5,86%,78%
16,Troy,frc9401,Midas' Mayhem,Missouri,1,8,2,0,3,2,0,4.0,80%,60%
17,Becker,frc4607,C.I.S.,Minnesota,2,7,2,0,0,2,0,3.5,78%,0%
18,Rockford,frc2290,FLYT,Illinois,1,7,2,0,1,2,0,9.0,78%,33%
19,Whitewater,frc6574,Ferradermis,Wisconsin,1,6,3,0,5,1,0,13.0,67%,83%
20,Waupaca,frc8700,W.I.R.E.D,Wisconsin,1,6,3,0,1,2,0,13.0,67%,33%
21,Milwaukee,frc1714,MORE Robotics,Wisconsin,1,6,3,0,0,2,0,22.0,67%,0%
22,Davenport,frc6317,Disruptive Innovation,Iowa,1,8,4,0,1,2,0,8.0,67%,33%
23,DeKalb,frc5934,Crowbotics,Illinois,1,6,4,0,2,2,0,8.0,60%,50%
24,Janesville,frc3692,Rock N' Robotics,Wisconsin,1,5,4,0,0,0,0,22.0,56%,nan%
25,Hartford,frc1091,Oriole Assault,Wisconsin,1,5,4,0,0,0,0,29.0,56%,nan%
26,Middleton,frc1306,BadgerBOTS,Wisconsin,1,5,4,0,0,2,0,19.0,56%,0%
27,Greendale,frc8701,GRAFFITI,Wisconsin,1,5,4,0,0,2,0,20.0,56%,0%
28,Rockford,frc4693,Talk Nerdy to Me,Minnesota,2,5,4,0,0,0,0,13.5,56%,nan%
29,Taipei,frc6947,Savage Tumaz,Taipei Special Municipality,1,5,5,0,2,2,0,13.0,50%,50%
30,Sheboygan,frc6381,Red Raider Robotics,Wisconsin,2,9,9,0,2,2,0,31.5,50%,50%
31,Burnsville,frc3184,Blaze Robotics,Minnesota,1,5,6,0,1,2,0,17.0,45%,33%
32,Muskego,frc6421,WarriorBots,Wisconsin,2,9,12,0,0,2,0,29.5,43%,0%
33,Williamsfield,frc7417,Bionic Bombers,Illinois,1,5,7,0,0,0,0,22.0,42%,nan%
34,Queretaro,frc3354,PrepaTec - TecDroid,Querétaro,1,5,7,0,0,2,0,23.0,42%,0%
35,Mumbai,frc6024,R Factor,Maharashtra,1,4,6,0,0,0,0,34.0,40%,nan%
36,Freedom,frc6318,FE Freedom Engineers,Wisconsin,1,3,6,0,0,0,0,43.0,33%,nan%
37,Cuernavaca,frc5948,PrepaTec - Lebotics,Morelos,1,4,7,1,3,2,0,20.0,33%,60%
38,New Berlin,frc5148,New Berlin Blitz,Wisconsin,1,3,6,0,0,0,0,38.0,33%,nan%
39,Waukesha,frc2062,CORE 2062,Wisconsin,1,2,7,0,0,0,0,42.0,22%,nan%
40,Holmen,frc6166,Thorobotics,Wisconsin,1,1,8,0,0,0,0,51.0,11%,nan%

In [8]:
url = f'https://www.thebluealliance.com/api/v3/event/{EVENT_KEY}/matches/simple'
resp = util.call_tba_api(url).json()
for match in resp:
    if match['match_number'] in [7, 15, 22, 30, 45, 54, 62, 68, 79, 89]:
        print('Match', match['match_number'])
        print('  Red:')
        for team in match['alliances']['red']['team_keys']:
            print('    ', team, df[df['key'] == team].index[0] + 1) 
        print('  Blue:')
        for team in match['alliances']['blue']['team_keys']:
            print('    ', team, df[df['key'] == team].index[0] + 1) 
    # print(match['key'], match['alliances']['red']['team_keys'], match['alliances']['blue']['team_keys'], match['winning_alliance'])